trigger:
- master

strategy:
  matrix:
    linux:
      VM_IMAGE: ubuntu-16.04
    mac:
      VM_IMAGE: macOS-10.14
    windows:
      VM_IMAGE: windows-2019

pool:
  vmImage: $(VM_IMAGE)

variables:
  DISPLAY: ':99.0'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js 10.x'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    npm install -g vsce
  displayName: Install vsce

- bash: npm ci
  displayName: Install dependencies

- bash: npx gulp tslint
  displayName: Run tslint

- bash: vsce package
  displayName: Package extension
