trigger:
- master

strategy:
  matrix:
    Linux:
      VM_IMAGE: ubuntu-16.04
    MacOS:
      VM_IMAGE: macOS-10.14
    Windows:
      VM_IMAGE: windows-2019

pool:
  vmImage: $(VM_IMAGE)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js 10.x'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    npm ci
    npm install -g vsce
  displayName: Install dependencies and tools

- bash: npx gulp tslint
  displayName: Run tslint

# - bash: npm run test
#   displayName: Run tests
#   env:
#     DISPLAY: ':99.0'

- bash: vsce package
  displayName: Package extension

- publish: $(Build.SourcesDirectory)/*.vsix
  artifact: vsix
  displayName: Package VSIX
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
